[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "20"
  BETTER_AUTH_SECRET = "your-strong-secret-here-min-32-chars"
  NEXT_PUBLIC_APP_URL = "https://your-netlify-site.netlify.app"
  BETTER_AUTH_URL = "https://your-netlify-site.netlify.app"
